site_name: Global Documentation
nav:
  - 'index.md'
  - 'Zero downtime deployment':
      - Blue Green deployment: 'blue-green-deployment.md'
  - 'DevOps':
      - Docker: docker.md
  - 'NoSQL':
    - MongoDB : mongodb.md
  - 'Documentation':
      - How to add documentation: how-to-add-documentation.md
theme: readthedocs
