site_name: Global Documentation
nav:
  - 'index.md'
  - 'Production':
      - Production Ready: 'production/production-ready.md'
  - 'DevOps':
      - Docker: docker.md
      - Blue Green deployment: 'blue-green-deployment.md'
      - MySQL Container: mysql.md
      - MongoDB Container: mongodb.md
  - 'Api Documentation':
    - Swagger : swagger.md
  - 'Documentation':
      - How to add documentation: how-to-add-documentation.md
theme: readthedocs
