site_name: Global Documentation
nav:
  - 'index.md'
  - 'Workflow':
      - Plan: 'workflow/plan.md'
      - Development: 'workflow/development.md'
      - Continuous Integration: 'workflow/continuous-integration.md'
      - Deployment: 'workflow/deployment.md'
  - 'Zero downtime deployment':
      - Blue Green deployment: 'blue-green-deployment.md'
  - 'DevOps':
      - Docker: docker.md
  - 'SQL':
    - MySQL : mysql.md
  - 'NoSQL':
    - MongoDB : mongodb.md
  - 'Api Documentation':
    - Swagger : swagger.md
  - 'Documentation':
      - How to add documentation: how-to-add-documentation.md
theme: readthedocs
